services:
    Samsonasik\Bundle\SampleBundle\Service\Wisdom:
      class: Samsonasik\Bundle\SampleBundle\Service\Wisdom

    Samsonasik\Bundle\SampleBundle\Service\HelloService:
       class: Samsonasik\Bundle\SampleBundle\Service\HelloService
       arguments:
          $wisdom: '@Samsonasik\Bundle\SampleBundle\Service\Wisdom'
