services:
    SampleBundle\Service\Wisdom:
      class: SampleBundle\Service\Wisdom

    SampleBundle\Service\HelloService:
       class: SampleBundle\Service\HelloService
       arguments:
          $wisdom: '@SampleBundle\Service\Wisdom'
